version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery:
    build: .
    environment:
      - RUN_WORKER=true
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A Dudo_dent beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
