version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=dudo_dent.settings
      - PYTHONPATH=/app
    restart: always

  celery:
    build: .
    environment:
      - RUN_WORKER=true
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A dudo_dent beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
