# Generated by Django 5.2 on 2025-05-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
