# Generated by Django 5.2 on 2025-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
