# Generated by Django 5.2 on 2025-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_availabilityrule_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='weekdays',
            field=models.CharField(choices=[('1', 'Mon'), ('2', 'Tue'), ('3', 'Wed'), ('4', 'Thu'), ('5', 'Fri'), ('6', 'Sat'), ('7', 'Sun')], max_length=3),
        ),
    ]
