# Generated by Django 5.2 on 2025-07-24 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_availabilityrule_weekdays'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('dentist', 'date', 'start_time')},
        ),
    ]
