# Generated by Django 5.2 on 2025-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_nurseprofile_user_workprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dentist', 'Dentist'), ('patient', 'Patient'), ('nurse', 'Nurse'), ('admin', 'Admin')]),
        ),
    ]
