# Generated by Django 5.2 on 2025-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patient',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('dentist', 'Dentist'), ('patient', 'Patient'), ('secretary', 'Secretary')], default='patient', max_length=20),
        ),
    ]
