# Generated by Django 5.2 on 2025-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprofile',
            name='google_calender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
