# Generated by Django 5.2 on 2025-07-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workprofile_google_calender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workprofile',
            old_name='google_calender_id',
            new_name='google_calendar_id',
        ),
    ]
