# Generated by Django 5.2 on 2025-07-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_age_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name']},
        ),
    ]
