# Generated by Django 5.2 on 2025-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='personal_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
