# Generated by Django 5.2 on 2025-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
