# Generated by Django 5.2 on 2025-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0002_procedure_description'),
        ('visits', '0002_visit_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='visits', to='procedures.procedure'),
        ),
    ]
