# Generated by Django 5.2 on 2025-05-29 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_visit_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
